### ISSUE TITLE
A Bug in SearchJavaMethods

### ISSUE THREAD

**Issue by N1rv0us** [2Y2s1mple/JebScript#1]
### What Bug
I found that the order of retrieval is class -> method, as shown in the following code :
Line  105 in SearchJavaMethods.py
```        
       for unit in self.dexunits:
            assert isinstance(unit, IDexUnit)
            # print("unit") # for debug potential crash
            if unit.getName() != "Bytecode": continue

            for clazz in unit.getClasses():
                assert isinstance(clazz, IDexClass)
                sourceIndex = clazz.getSourceStringIndex()
                clazzAddress = clazz.getAddress()
                #if "" != clazzAddress: continue
                DexAnnotationsDirectory = clazz.getAnnotationsDirectory()
                if chosen in [1, 2]:
                    for mtd in clazz.getMethods():
                        assert isinstance(mtd, IDexMethod)
```

Such a traversal will result in not being able to retrieve methods in classes that are not implemented in apk/dex, e.g. `Landroid/app/PendingIntent;->getActivity`
And this method should have been able to be retrieved.

### Why Bug

I tried to write some tests, as follow:
```
    def test(self):
        msign = "Landroid/app/PendingIntent;->getActivity(Landroid/content/Context;ILandroid/content/Intent;I)Landroid/app/PendingIntent;"
        csign = "Landroid/app/PendingIntent;"
        method = self.dexUnit.getMethod(msign)
        clz = self.dexUnit.getMethod(csign)
        print method
        print method.getClassTypeSignature(False)
        print method.getClassTypeIndex()
        print method.getClassType()

        print self.dexUnit.getType(method.getClassTypeIndex())
        print self.dexUnit.getType(method.getClassTypeIndex()).getImplementingClass()

        print self.dexUnit.getType(method.getClassTypeIndex()).isClass()
```

and Here is result:

```
Method:#26053,name=getActivity,address=Landroid/app/PendingIntent;->getActivity(Landroid/content/Context;ILandroid/content/Intent;I)Landroid/app/PendingIntent;
Landroid/app/PendingIntent;
6051
Type:#6051,name=PendingIntent,address=Landroid/app/PendingIntent;
Type:#6051,name=PendingIntent,address=Landroid/app/PendingIntent;
None
True
```

The target method exists in dexUnit, but not the target class.

### How to Fix

Suggest changing the search order to iterate through dexUnit.getMethods/dexUnit.getTypes.

### Some useful Docs
* IDexUnit doc : https://www.pnfsoftware.com/jeb2/apidoc/reference/com/pnfsoftware/jeb/core/units/code/android/IDexUnit.html
* IDexMethod doc : https://www.pnfsoftware.com/jeb2/apidoc/reference/com/pnfsoftware/jeb/core/units/code/android/dex/IDexMethod.html

**Comment by 2Y2s1mple** [comment]
[SearchJavaMethods.py](https://github.com/2Y2s1mple/JebScript/blob/master/SearchJavaMethods.py) aims to find methods implemented by developer.
Try [SensitiveMethod.py](https://github.com/2Y2s1mple/JebScript/blob/master/SensitiveMethod.py) for framework API instead.

Thinks for the report  ❤️
